# Generated by Django 3.2.13 on 2022-05-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
